apiVersion: v1
kind: Service
metadata:
  name: bsp-api-svc
  labels:
    app: bsp-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: bsp-api
